"""L

Revision ID: 564e0e6df47a
Revises: 
Create Date: 2025-12-17 06:51:52.123213

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '564e0e6df47a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
